name: deploy

on:
  push:
    branches:
      - main
      - feature/deployment-setup

jobs:     
  build:
    name: Build, push to registries, and deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Auth to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker for G-AR
      - name: Configure Docker for GAR
        run: gcloud auth configure-docker asia-docker.pkg.dev 

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build & push to Docker Hub and G-AR
      - name: Build and push to Docker Hub & GAR for backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packages/backend/Dockerfile
          push: true
          tags: |
            akaimnky/arkadia-backend:latest
            asia-south1-docker.pkg.dev/smart-rope-469816-u7/arkadia-docker/arkadia-backend:latest

      - name: Build and push to Docker Hub & GAR for bot
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packages/bot/Dockerfile
          push: true
          tags: |
            akaimnky/arkadia-bot:latest
            asia-south1-docker.pkg.dev/smart-rope-469816-u7/arkadia-docker/arkadia-bot:latest

      - name: Build and push to Docker Hub & GAR for frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packages/frontend/Dockerfile
          push: true
          tags: |
            akaimnky/arkadia-frontend:latest            
            asia-south1-docker.pkg.dev/smart-rope-469816-u7/arkadia-docker/arkadia-frontend:latest
